name: sagemaker-tutorial
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=10.2
  - pytorch=1.10
  - torchvision=0.11
  # This dependency must be constrained to specified version until
  # https://github.com/pytorch/pytorch/pull/69904 is released. See
  # https://stackoverflow.com/a/70520199/263264 for details.
  - setuptools=59.5.0
  - pip
  - pip:
    - sagemaker
    - sagemaker-training
    - pytorch-lightning==1.5.*
    - jsonargparse[signatures]==4.0.*
    - lightning-bolts==0.4.*
    - torchmetrics==0.6.*
    - fsspec[s3]
